-- Fix passwords for all test users
-- Run this in phpMyAdmin SQL tab after selecting your database

-- Update all users with correct hash for Password123!
-- Hash generated by password_hash('Password123!', PASSWORD_BCRYPT)
-- ALWAYS use WHERE clause to avoid updating all rows accidentally

UPDATE users
SET `password` = '$2y$10$hsUZAfURxiajmfNPH/X3ZOgqbA7uIOS61RdiSiWH.iV4yNFqEgdJa'
WHERE email = 'john.doe@ashesi.edu.gh';

UPDATE users
SET `password` = '$2y$10$hsUZAfURxiajmfNPH/X3ZOgqbA7uIOS61RdiSiWH.iV4yNFqEgdJa'
WHERE email = 'alice.johnson@ashesi.edu.gh';

UPDATE users
SET `password` = '$2y$10$hsUZAfURxiajmfNPH/X3ZOgqbA7uIOS61RdiSiWH.iV4yNFqEgdJa'
WHERE email = 'bob.wilson@ashesi.edu.gh';

UPDATE users
SET `password` = '$2y$10$hsUZAfURxiajmfNPH/X3ZOgqbA7uIOS61RdiSiWH.iV4yNFqEgdJa'
WHERE email = 'jane.smith@ashesi.edu.gh';

UPDATE users
SET `password` = '$2y$10$hsUZAfURxiajmfNPH/X3ZOgqbA7uIOS61RdiSiWH.iV4yNFqEgdJa'
WHERE email = 'michael.brown@ashesi.edu.gh';

-- Verify the update
SELECT name, email, role, LEFT(password, 20) as password_preview FROM users;
